# MQTBench suite for Graphix simulators

#### Circuit characterization

In [9]:
from graphix_mqtbench import characterize_all_benchmarks, OptimizationPass

n_qubits = 4

characterize_all_benchmarks(n_qubits, optim_passes=[OptimizationPass.M, OptimizationPass.P, OptimizationPass.PM])

                      Circuit                  Transpilation             \
                    Benchmark # Qubits # Gates     Max Space # Commands
0                          ae        4     128             8       1038
1       bmw_quark_cardinality        4     123             6        876
2            bmw_quark_copula        4      72             6        524
3                          bv        4       4             6         17
4     cdkm_ripple_carry_adder        4       7            22        182
5                          dj        4      16             6        110
6            draper_qft_adder        4      29             6        236
7                  full_adder        4       6            22        172
8                         ghz        4       4             6         34
9                  graphstate        4       8             5         20
10                     grover        4     132            22       1144
11                 HALF_ADDER        4    <NA>          <NA>       <NA>
12                        hhl        4      49             8        400
13  HRS_CUMULATIVE_MULTIPLIER        4    <NA>          <NA>       <NA>
14              modular_adder        4      31             6        236
15                 multiplier        4      42            22        430
16                       qaoa        4      24             6        196
17                        qft        4      34             6        280
18               qftentangled        4      38             6        314
19                        qnn        4      27             8        246
20                   qpeexact        4      25             6        200
21                 qpeinexact        4      37             6        296
22                      qwalk        4     250            22       2524
23              randomcircuit        4     108            22       1052
24          rg_qft_multiplier        4      40             6        336
25                       SHOR        4    <NA>          <NA>       <NA>
26     vbe_ripple_carry_adder        4       6            22        172
27               vqe_real_amp        4      25             8        314
28                    vqe_su2        4      89             6        730
29              vqe_two_local        4      34             8        404
30                     wstate        4      13             8        125

   Space minimization            Pauli presimulation             \
            Max Space # Commands           Max Space # Commands
0                   5        778                  25         76
1                   5        656                  37        138
2                   5        396                  30        124
3                   5         17                   4          8
4                   5        163                  16         56
5                   5         89                   4         13
6                   5        180                  10         33
7                   5        156                  16         56
8                   5         32                   4         13
9                   5         24                   4         16
10                  5        867                  51        312
11               <NA>       <NA>                <NA>       <NA>
12                  5        306                  21         73
13               <NA>       <NA>                <NA>       <NA>
14                  5        180                  10         33
15                  5        343                  25         96
16                  5        151                  13         43
17                  5        212                  19         74
18                  5        236                  22         85
19                  5        197                  20        124
20                  5        154                  10         30
21                  5        224                  16         49
22                  5       1919                 124        480
23                  5        824                  71        426
24                  5        252                  21         87
25               <NA>       <NA>                <NA>       <NA>
26                  5        156                  16         56
27                  5        263                  20        121
28                  5        551                  36        230
29                  5        326                  20        121
30                  5        110                  10         49

   Pauli presimulation + Space minimization
                                  Max Space # Commands
0                                        16         76
1                                        12        138
2                                        10        124
3                                         4          8
4                                        10         56
5                                         4         13
6                                         4         33
7                                         9         56
8                                         4         13
9                                         4         16
10                                       32        312
11                                     <NA>       <NA>
12                                       10         73
13                                     <NA>       <NA>
14                                        4         33
15                                        7         96
16                                        7         43
17                                       10         74
18                                       11         85
19                                       11        124
20                                        4         30
21                                        6         49
22                                       58        480
23                                       50        426
24                                       13         87
25                                     <NA>       <NA>
26                                        9         56
27                                       13        121
28                                       17        230
29                                       13        121
30                                        7         49

In [1]:
from graphix_mqtbench import read_results
from pathlib import Path 

folder = Path.cwd().parents[0] / ".benchmarks/"
read_results(folder.rglob("*example_4qubits.json")).xs("mean", level=1, axis=1)

OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.

Backend                           density_matrix-M  statevector-M
Benchmark               # Qubits
ae                      4                 0.073473       0.047880
bmw_quark_cardinality   4                 0.060189       0.039151
bmw_quark_copula        4                 0.037105       0.023318
bv                      4                 0.001413       0.000771
cdkm_ripple_carry_adder 4                 0.014624       0.008628
dj                      4                 0.007333       0.004531
draper_qft_adder        4                 0.015901       0.009820
full_adder              4                 0.014361       0.008306
ghz                     4                 0.002275       0.001265
graphstate              4                 0.001340       0.000752
grover                  4                 0.079319       0.048728
hhl                     4                 0.027702       0.016891
modular_adder           4                 0.015875       0.009749
multiplier              4                 0.030597       0.020914
qaoa                    4                 0.013704       0.008238
qft                     4                 0.019362       0.011860
qftentangled            4                 0.021015       0.013018
qnn                     4                 0.018057       0.011778
qpeexact                4                 0.013350       0.008216
qpeinexact              4                 0.019620       0.012264
qwalk                   4                 0.174473       0.108871
randomcircuit           4                 0.075676       0.046526
rg_qft_multiplier       4                 0.022822       0.013813
vbe_ripple_carry_adder  4                 0.014050       0.008436
vqe_real_amp            4                 0.023610       0.014365
vqe_su2                 4                 0.056781       0.032706
vqe_two_local           4                 0.028698       0.017689
wstate                  4                 0.009306       0.005849

For larger number of qubits, we just minimize space

In [12]:
from graphix_mqtbench import characterize_all_benchmarks, OptimizationPass

n_qubits = 6

characterize_all_benchmarks(n_qubits, optim_passes=[OptimizationPass.M])

                      Circuit                  Transpilation             \
                    Benchmark # Qubits # Gates     Max Space # Commands
0                          ae        6     528            10       4338
1       bmw_quark_cardinality        6     195             8       1380
2            bmw_quark_copula        6     150             8       1050
3                          bv        6       7             8         26
4     cdkm_ripple_carry_adder        6      13            24        354
5                          dj        6      24             8        162
6            draper_qft_adder        6      66             8        552
7                  full_adder        6      13            24        354
8                         ghz        6       6             8         54
9                  graphstate        6      12             7         30
10                     grover        6    1170            24       9916
11                 HALF_ADDER        6    <NA>          <NA>       <NA>
12                        hhl        6     135            10       1144
13  HRS_CUMULATIVE_MULTIPLIER        6    <NA>          <NA>       <NA>
14              modular_adder        6      67             8        552
15                 MULTIPLIER        6    <NA>          <NA>       <NA>
16                       qaoa        6      60             8        512
17                        qft        6      81             8        684
18               qftentangled        6      87             8        738
19                        qnn        6      41            10        374
20                   qpeexact        6      79             8        656
21                 qpeinexact        6      86             8        708
22                      qwalk        6    1931            24      17256
23              randomcircuit        6     144            24       1603
24          RG_QFT_MULTIPLIER        6    <NA>          <NA>       <NA>
25                       SHOR        6    <NA>          <NA>       <NA>
26     VBE_RIPPLE_CARRY_ADDER        6    <NA>          <NA>       <NA>
27               vqe_real_amp        6      39            10        486
28                    vqe_su2        6     135             8       1110
29              vqe_two_local        6      69            10        786
30                     wstate        6      21            10        203

   Space minimization
            Max Space # Commands
0                   7       3226
1                   7       1032
2                   7        786
3                   7         26
4                   7        315
5                   7        131
6                   7        414
7                   7        315
8                   7         50
9                   7         36
10                  7       7329
11               <NA>       <NA>
12                  7        858
13               <NA>       <NA>
14                  7        414
15               <NA>       <NA>
16                  7        382
17                  7        510
18                  7        548
19                  7        299
20                  7        490
21                  7        528
22                  7      12837
23                  7       1281
24               <NA>       <NA>
25               <NA>       <NA>
26               <NA>       <NA>
27                  7        405
28                  7        837
29                  7        615
30                  7        178

In [13]:
from graphix_mqtbench import read_results
from pathlib import Path 

folder = Path.cwd().parents[0] / ".benchmarks/"
read_results(folder.rglob("*example_6qubits.json")).xs("mean", level=1, axis=1)

Backend                           density_matrix-M  statevector-M
Benchmark               # Qubits
ae                      6                 0.871116       0.199304
bmw_quark_cardinality   6                 0.276617       0.061679
bmw_quark_copula        6                 0.215777       0.047264
bv                      6                 0.008209       0.001196
cdkm_ripple_carry_adder 6                 0.093513       0.017591
dj                      6                 0.032856       0.006949
draper_qft_adder        6                 0.103941       0.023981
full_adder              6                 0.077827       0.017836
ghz                     6                 0.011402       0.002035
graphstate              6                 0.006252       0.001172
grover                  6                 1.942888       0.433786
hhl                     6                 0.232486       0.055091
modular_adder           6                 0.111415       0.023324
qaoa                    6                 0.099532       0.027074
qft                     6                 0.138773       0.029197
qftentangled            6                 0.144267       0.031644
qnn                     6                 0.078663       0.017597
qpeexact                6                 0.126332       0.028553
qpeinexact              6                 0.138755       0.033553
qwalk                   6                 3.406750       0.742738
randomcircuit           6                 0.351584       0.075689
vqe_real_amp            6                 0.109070       0.030394
vqe_su2                 6                 0.230187       0.052532
vqe_two_local           6                 0.165923       0.033125
wstate                  6                 0.046579       0.009715